apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: foodgram
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: rybakodmitry2077/foodgram-st:v.2.1
        command: ["python",  "manage.py", "migrate", "--no-input"]
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
      restartPolicy: OnFailure
  backoffLimit: 4
