apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: foodgram
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard