apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: foodgram
spec:
  type: ClusterIP
  selector:
    app: foodgram-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
