apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: foodgram
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard