apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "back.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "back.selectorLabels" . | indent 4 }}
  ports:
    - protocol: {{ .Values.service.ports.protocol | default "TCP" }}
      port: {{ .Values.service.ports.port | default 8000 }}
      targetPort: {{ .Values.service.ports.targetPort | default 8000 }}