apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "back.staticName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "back.labels" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.static.storage }}
  storageClassName: {{ .Values.persistence.static.storageClassName }}
