apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: foodgram
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres