deployment:
  replicas: 3
  image:
    name: rybakodmitry2077/foodgram-st
    tag: v.2.1
  ports:
    containerPort: 8000
  volumeMounts:
    staticMountPath: /app/backend_static/
    mediaMountPath: /app/backend_media/
  env:
    values: {}
    config:
      DB_PORT: DB_PORT
      DB_HOST: DB_HOST
    secret:
      DB_NAME: postgres-name
      DB_USER: postgres-user
      DB_PASSWORD: postgres-password
  pvc:
    static:
      pvcName: "static-pvc"
    media:
      pvcName: "media-pvc"

importDataJob:
  restartPolicy: OnFailure
  backoffLimit: 4

jobCollectstatic:
  mountPath: /app/backend_static/
  restartPolicy: OnFailure

jobMigrate:
  restartPolicy: OnFailure
  backoffLimit: 4

service:
  type: ClusterIP
  ports:
    protocol: TCP
    port: 8000
    targetPort: 8000

persistence:
  static:
    storage: 5Gi
    storageClassName: "standard"
  media:
    storage: 10Gi
    storageClassName: "standard"