apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "postgres.labels" . | indent 4 }}
data:
{{- range $key, $val := .Values.configMap }}
  {{ $key }}: {{ $val | quote }}
{{- end }}