apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "postgres.labels" . | indent 4 }} 
type: Opaque
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote}}
{{- end }}
