apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "postgres.labels" . | indent 4 }} 
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  - port: {{ .Values.service.ports.port }}
    targetPort: {{ .Values.service.ports.targetPort }}
  selector:
{{ include "postgres.selectorLabels" . | indent 4 }}