apiVersion: v1
kind: Service
metadata:
  name: {{ include "front.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "front.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "front.selectorLabels" . | indent 4 }}
  ports:
    - protocol: {{ .Values.service.ports.protocol }}
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
