apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: foodgram
data:
    DB_HOST: "postgres-service.foodgram.svc.cluster.local"
    DB_PORT: "5432"
    DB_NAME: "foodgramDB"
    DB_USER: "postgres"
