apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: foodgram
data:
  nginx.conf: |
    server {
        listen 80;
        client_max_body_size 10M;
        server_tokens off;

        location /backend_media/ {
            root /var/html/;
        }

        location /api/ {
            proxy_pass http://backend-service:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /admin/ {
            proxy_pass http://backend-service:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/docs/ {
            root /usr/share/nginx/html;
            try_files $uri $uri/redoc.html;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
            # Убрать proxy_set_header - они не нужны для статики
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;  # Исправленный путь
        }

        location /backend_static/ {
            root /var/html/;
        }
    }